function isLocalStorageNameSupported() {var testKey = 'yRDtestKey', storage = window.localStorage;try {storage.setItem(testKey, '1');storage.removeItem(testKey);return true;} catch (error) {return false;}}var pl={},endpoint="https://d3fpy29ak9d24c.cloudfront.net/track.gif";
function guid(){var d = new Date().getTime();var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {var r = (d + Math.random()*16)%16 | 0;d = Math.floor(d/16);return (c=='x' ? r : (r&0x3|0x8)).toString(16);});return uuid;}
function getCookie(e){var n=" "+document.cookie,l=" "+e+"=",t=null,i=0,g=0;if(n.length>0&&(i=n.indexOf(l),-1!=i&&(i+=l.length,g=n.indexOf(";",i),-1==g&&(g=n.length),t=unescape(n.substring(i,g)))),t&&t.length>0&&t.indexOf("=")>0)for(var o=t.split("&"),r={},u=0;u<o.length;u++){var f=o[u].split("=");r[f[0]]=f[1]}else r=t&&t.length>0?t:null;return r}
function setCookie(e,t,o,a,n,s){var c=new Date;c.setDate(c.getDate()+(parseInt(o)||0));var i=c,p=document.location.host.split("."),r="."+p[p.length-2]+"."+p[p.length-1];document.cookie=e+"="+escape(t)+(i?"; expires="+i:"")+"; path="+(a?a:"/")+"; domain="+(n?n:r)+(s?"; secure":"")}
function getParameterByName(name) {name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),results = regex.exec(location.search);var resp="";try{resp=(typeof(results)=="undefined" || results === null) ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));}catch(e){resp="";}return resp;}
function getUserID(){var uid=null;if(localStorage && isLocalStorageNameSupported()){if(localStorage.getItem('guid-yOrb')){uid=localStorage.getItem('guid-yOrb') || null;}}else if(getCookie("yOrbRD")!=null){uid=getCookie("yOrbRD")["guid"] || null;}return uid;}
function refreshguid(guid){if(localStorage && isLocalStorageNameSupported()){localStorage.setItem('guid-yOrb',guid);}setCookie("yOrbRD","guid=" + guid,365,"/");pl.uid=guid;try{var yooxbizi=document.createElement("iframe");yooxbizi.src="//media.yoox.biz/newsl/rd/yorb.htm?yorbid=" + pl.uid;document.firstChild.appendChild(yooxbizi);}catch(e){}storeevent();}
function clearvalues(valore){try{if(typeof(valore)!="undefined" && valore!=null && valore!="undefined" && valore!="null"){return escape(valore.toString().trim());}}catch(e){return escape(valore);}return "";}
function guidverify(data){var uid=null;if(typeof(data)!="undefined" && data!=null){uid=data.id;}else if(typeof(pl.uid)=="undefined" || pl.uid==null || pl.uid==""){uid=guid();}else{uid=pl.uid;}refreshguid(uid);}
function guiddbcheck(data){var uid=null;if(typeof(data)!="undefined" && data!=null){uid=data.id;}else if(typeof(pl.uid)=="undefined" || pl.uid==null || pl.uid==""){uid=guid();}else{uid=pl.uid;}refreshguid(uid);}
function getGuid(){if(pl.e!=null && pl.e!=""){var script = document.createElement('script');script.src = 'https://secure.social.yoox.it/yprediction.api/history/getguid?e=' + clearvalues(pl.e) + '&sitecode=' + pl.sitecode + '&callback=guidverify';document.getElementsByTagName('head')[0].appendChild(script);}else{guidverify(null);}}
function setGuidVerify(data){if(typeof(data)!="undefined" && data!=null){if(data.resp=="collision"){pl.uid=guid();refreshguid(pl.uid);}if(data.resp=="existing" && typeof(data.guid)!="undefined" && data.guid!=null && data.guid!="" && data.guid!=pl.uid){pl.uid=data.guid;refreshguid(pl.uid);}}}
function setGuid(guid,sitecode,e){if(e!=null && e!=""){var script = document.createElement('script');script.src = 'https://secure.social.yoox.it/yprediction.api/history/setguid?guid=' + guid + '&e=' + clearvalues(e) + '&sitecode=' + sitecode + '&callback=setGuidVerify';document.getElementsByTagName('head')[0].appendChild(script);}}
function storeevent(){pl.url=getParameterByName("u");pl.user=getParameterByName("userid");pl.cod10=getParameterByName("cod10");pl.size=getParameterByName("size");pl.ts=Math.random();var sID=getParameterByName("sid");if(getParameterByName("brand")!=""){pl.brand=getParameterByName("brand");}if(getParameterByName("micro")!=""){pl.micro=getParameterByName("micro");}var getpl="";for(var key in pl){getpl+=key + "=" + clearvalues(pl[key]);getpl+="&";}if(pl.cod10!=null && pl.cod10!="" && pl.event=="itemview"){track[0]=document.createElement("img");var GETvars="guid=" + pl.uid + "&sitecode=" + pl.sitecode + "&cod10=" + pl.cod10 + "&ts=" + Math.random();track[0].src="https://secure.social.yoox.it/yprediction.api/history/?" + GETvars;}if(pl.e!=null && pl.e!="" && pl.event=="userlogged"){setGuid(pl.uid,pl.sitecode,pl.e);}if(pl.cod10!=null && pl.cod10!="" && pl.event=="purchased"){track[4]=document.createElement("img");var GETvars="guid=" + pl.uid + "&sitecode=" + pl.sitecode + "&cod10=" + pl.cod10 + "&ts=" + Math.random();track[4].src="https://secure.social.yoox.it/yprediction.api/history/setpurchase?" + GETvars;}track[1]=document.createElement("img");track[1].src=endpoint+"?" + getpl;var s=new easyXDM.Socket({remote : "",onReady:  function(){s.postMessage(pl.uid + ";" + sID);}});}
var track=[];
pl.uid=getUserID();
pl.event=getParameterByName("event");
pl.e=getParameterByName("e");
pl.sitecode=getParameterByName("sitecode");
if(pl.uid==null || pl.event=="userlogged"){if(pl.e!=null && pl.e!="" && pl.uid!=null && pl.uid!="" && pl.event=="userlogged"){track[3]=document.createElement("img");var GETvars="event=userlogged&uid=" + pl.uid + "&sitecode=" + pl.sitecode + "&e=" + clearvalues(pl.e) + "&ts=" + Math.random();track[3].src=endpoint+"?" + GETvars;}getGuid();}else{refreshguid(pl.uid);}